# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bookswap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bookswap
  pod 'Firebase/Core'

  target 'bookswap-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bookswapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end